### PR TITLE
making a clone of a New York Times article page

### PR DESCRIPTION
**Pull request by alvinlouis29**
The goal of this project was to create a clone page that looks like the new york times article page using CSS and Html

### CODE REVIEW

**Comment by pelzolga123** [comment]
### Hi Team!
#### I am marking this Review request as invalid due to following reasons:

* README file is not descriptive
* `stickler.yml` is showing errors

Kindly fix the above issues and send another code review request.
If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello Team! My name is Mario Enrique. __Congratulations on your project!__  It looks great and _almost_ ready to be approved. :ok_hand::ok_hand::ok_hand:
However some changes are needed. 

## Changes required:heavy_exclamation_mark:
- [ ] Avoid using `position: absolute` in this project, please position all your elements using either `float`, `flex` or `grid`. `Position absolute` causes display errors on bigger screens. [See screenshot](https://raw.githubusercontent.com/MarioDena/reviewImages/master/review%201.jpg) 

- [ ] Your sections "Most popular" and "More in Space and Astronomy" Display incorrectly on higher resolutions. [Project screenshot](https://raw.githubusercontent.com/MarioDena/reviewImages/master/review%202%20original.jpg) | [Original page screenshot](https://raw.githubusercontent.com/MarioDena/reviewImages/master/review%202.jpg_) (You can use the Firefox developer tools to test your projects on higher resolutions than your native one)

- [ ] Please remove all comments on your code. There are several comments on both your `HTML` and your `CSS` files. ![Img][img1]

### Optional changes
- [ ] `[OPTIONAL]` Consider using a code-formatter on your files, this will give you a more streamlined spacing. [Example](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) 

Keep up the good work! After making the mentioned changes, please resubmit your project for review.

Cheers and Happy coding!:clap::clap::clap:

Code review by __Mario Enrique Delgado Naranjo__

[img1]: https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png

**Comment by uryelah** [comment]
### **Pull Request under the review by Sarah Uryelah Silva Chamorro (TSE)**

**Comment by uryelah** [comment]
Hello **Kamil Adewale** & **Alvin Louis Ssegawa**, I'm Sarah, your reviewer for this PR .

First of all, you did an amazing job completing the required changes, so, kudos to you both 🥇 

**Congrats for:**
- making the page look like a real clone of the original
- great descriptive CSS class names
- descriptive commit messages
- a very tidy code
- great README.md file


**Now, there's a small thing missing:**
The Pathwright, at Additional Microverse Requirements, indicates that you should use [semantic HTML.](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/) 
semantic

But since this was not noticed at the first review, we apologize for that 😿 , this is now an optional requirement.  And that means that...

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

**Optional changes**

- [ ] [OPTIONAL] Make it semantic!

[A semantic element clearly describes its meaning to both the browser and the developer.](https://www.w3schools.com/html/html5_semantic_elements.asp)

With semantic HTML your project will look way more professional and easy to read.
-  Consider changing some of the `<div>`s used to `<article>`s or `<section>`s
-  [Check](https://www.youtube.com/watch?v=swWeWesZVZU) [these resources](https://bitsofco.de/sectioning-content-in-html5/) to know more about articles and sections tags
-  Give your footer area some love ❤️  with a `<footer>` tag
-  Make your middle container shine 🌟  with s `<main>` tag
    
   
- [ ]  [OPTIONAL] Show off your great work

-  Your project looks amazing 👓 , how about adding [a screenshot of it to your readme file](https://stackoverflow.com/questions/14494747/add-images-to-readme-md-on-github)?

-------

**Keep being awesome devs and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
